name: polyID
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - rdkit
  - scikit-learn
  - tqdm
  - cudatoolkit
  - ipykernel
  - jupyterlab
  - tensorflow=2.10
  - pip
  - pip:
    - nfp
    - m2p
    - polyid
    - tensorflow-addons
