name: polyID
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pandas
  - numpy
  - rdkit
  - scikit-learn
  - pip
  - tqdm
  - cudatoolkit
  - ipykernel
  - pip
  - pip:
    - nfp
    - m2p
    - tensorflow
    - tensorflow-addons
